<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HEOVU1M" name="roi4cio.TestAddProduct" tests="11" failures="1" timestamp="2 Dec 2016 23:15:45 GMT" time="242.649" errors="0">
  <testcase name="testAddProductWithSameName" time="20.215" classname="roi4cio.TestAddProduct">
    <failure type="java.lang.AssertionError" message="Product with the same title couldn&#039;t be created expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Product with the same title couldn't be created expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at roi4cio.TestAddProduct.testAddProductWithSameName(TestAddProduct.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- testAddProductWithSameName -->
  <testcase name="testAddPdocutWithEmptyDeliveryAndCategory" time="20.374" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductWithFilledAllFields" time="25.970" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductCickOnYesInConfirmationPopupAfterErrors" time="24.992" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductWithEmptyMandatoryFields" time="19.795" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductWithoutCountry" time="24.261" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductWithEmptyCategory" time="19.911" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProduct" time="19.516" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductCickOnYesInConfirmationPopup" time="24.974" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductWithEmptyAllFields" time="22.945" classname="roi4cio.TestAddProduct"/>
  <testcase name="testAddProductConfirmationPopup" time="19.696" classname="roi4cio.TestAddProduct"/>
</testsuite> <!-- roi4cio.TestAddProduct -->
